org: leozenberg
app: notes-crud


service: notes-crud
frameworkVersion: "3"

custom:
  tableName: '${sls:stage}-notes'

provider:
  name: aws
  runtime: nodejs18.x
  profile: default
  region: us-east-1
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.NOTES}"
  environment:
    NOTES: ${self:custom.tableName}

functions:
  createNote:
    handler: create.handler
    description: Submit candidate information and starts interview process.
    events:
      - httpApi: 
          path: /new-note
          method: post

  getNotes:
    handler: list.handler
    events:
      - httpApi:
          path: /notes
          method: GET

  deleteNote:
    handler: delete.handler
    events:
      - httpApi:
          path: /notes/{id}
          method: DELETE


resources:
  Resources:
    Notes:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

